version: '3'
services:
  api:
    build: responder_app/
    ports:
      - "4000:80"
  jnb:
    build: jupyter_lab/
    ports:
      - "10000:8888"
      - "4040:4040"
    volumes:
      - .:/home/jovyan/work
    env_file:
      - ./config/shared_database.env
      - ./config/jupyter.env
    entrypoint: sh -c 'start-notebook.sh --NotebookApp.token=$$JUPYTER_PASSWORD'
  postgres:
    image: postgres:12.0-alpine
    ports:
      - "8001:5432"
    volumes:
      - ./services/postgres/:/docker-entrypoint-initdb.d/
      - pg_volume:/var/lib/postgresql
      - ./data/:/import_data/
    env_file:
      - ./config/shared_database.env
      - ./config/airflow_database.env
      - ./config/superset_database.env
  dash:
    build: dashboard/
    depends_on:
      - postgres
    ports:
      - "8050:8050"
  airflow:
    image: puckel/docker-airflow:1.10.4
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./config/airflow_container.env
      - ./config/shared_database.env
    volumes:
      - ./config/requirements.txt:/requirements.txt
      - ./dags/:/usr/local/airflow/dags
    command: webserver
  superset:
    image: amancevice/superset:0.34.1
    ports:
      - "8088:8088"
    depends_on:
        - postgres
    env_file:
        - ./config/superset_container.env
        - ./config/superset_database.env

volumes:
  pg_volume:
