version: '3'
services:
  api:
    build: responder_app/
    ports:
      - "4000:80"
  jnb:
    image: "jupyter/scipy-notebook:7254cdcfa22b"
    ports:
      - "10000:8888"
    volumes:
      - .:/home/jovyan/work
    env:
      - ./config/shared_database.env
  db:
    image: postgres:11.1-alpine
    ports:
      - "8001:5432"
    volumes:
      - ./services/postgres/:/docker-entrypoint-initdb.d/
      - pg_volume:/var/lib/postgresql
    env:
      - ./config/shared_database.env
  dash:
    build: dashboard/
    depends_on:
      - db
    ports:
      - "8050:8050"

volumes:
  pg_volume:
