version: '3'
services:
  api:
    build: responder_app/
    ports:
      - "4000:80"
  jnb:
    image: "jupyter/scipy-notebook:7254cdcfa22b"
    ports:
      - "10000:8888"
    volumes:
      - .:/home/jovyan/work
  db:
    image: postgres:11.1-alpine
    ports:
      - "8001:5432"
    volumes:
      - ./services/postgres/:/docker-entrypoint-initdb.d/
      - pg_volume:/var/lib/postgresql
  dash:
    build: dashboard/
    ports:
      - "8002:8050"

volumes:
  pg_volume:
